export const templates = [
  {
    for: [],
    category: "",
    name: "Blank board",
    columns: [],
  },
  {
    for: ["Student", "College student"],
    category: "School",
    name: "School planner",
    columns: [
      { name: "Math", emoji: "1f4d0" },
      { name: "English", emoji: "1f4d5" },
      { name: "Science", emoji: "1f9ea" },
      { name: "History", emoji: "1f30d" },
    ],
  },
  {
    for: ["Adult"],
    category: "Personal",
    name: "Trip planning",
    columns: [
      { name: "Destination", emoji: "2708" },
      { name: "Accommodations", emoji: "1f3e0" },
      { name: "Transportation", emoji: "2708" },
      { name: "Activities", emoji: "270c" },
      { name: "Packing checklist", emoji: "1f9f3" },
    ],
  },
  {
    for: ["Social media manager", "Influencer", "Digital marketer"],
    category: "Work",
    name: "Social media planner",
    columns: [
      { name: "Content Creation", emoji: "1f4f7" },
      { name: "Engagement", emoji: "1f49d" },
    ],
  },
  {
    for: ["Home cook", "Meal prepper", "Dietitian"],
    category: "Personal",
    name: "Meal planning",
    columns: [
      { name: "Breakfast", emoji: "1f95e" },
      { name: "Lunch", emoji: "1f96a" },
      { name: "Dinner", emoji: "1f372" },
      { name: "Snacks", emoji: "1f95b" },
      { name: "Grocery List", emoji: "1f6d2" },
    ],
  },
  {
    for: ["Individual", "Investor", "Financial planner"],
    category: "Personal",
    name: "Financial Goals",
    columns: [
      { name: "Savings", emoji: "1f4b0" },
      { name: "Investments", emoji: "1f4b8" },
      { name: "Debt Repayment", emoji: "1f4b7" },
      { name: "Budgeting", emoji: "1f4c3" },
      { name: "Financial Education", emoji: "1f9d2" },
    ],
  },
  {
    for: ["Parent", "Family member"],
    category: "Personal",
    name: "Family Chores",
    columns: [
      { name: "Cleaning", emoji: "1f9f9" },
      { name: "Cooking", emoji: "1f373" },
      { name: "Laundry", emoji: "1f9fc" },
      { name: "Errands", emoji: "1f3e0" },
      { name: "Organization", emoji: "1f5c2" },
    ],
  },
  {
    for: ["Parent", "Family member"],
    category: "Personal",
    name: "Fitness planner",
    columns: [
      { name: "Cardio", emoji: "1f3c3" },
      { name: "Strength Training", emoji: "1f4aa" },
      { name: "Flexibility", emoji: "1f9d8" },
      { name: "Nutrition", emoji: "1f96a" },
    ],
  },
  {
    for: ["Student", "College student"],
    category: "School",
    name: "Finals Week Planner",
    columns: [
      { name: "Study Schedule", emoji: "1f4da" },
      { name: "Subject 1", emoji: "1f4d0" },
      { name: "Subject 2", emoji: "1f4d5" },
      { name: "Subject 3", emoji: "1f9ea" },
      { name: "Subject 4", emoji: "1f30d" },
    ],
  },
  {
    for: ["Job seeker", "Professional", "Career coach"],
    category: "Personal",
    name: "Career Planning",
    columns: [
      { name: "Self-Assessment", emoji: "1f4cb" },
      { name: "Skills Development", emoji: "1f9d1" },
      { name: "Goal Setting", emoji: "1f4c8" },
      { name: "Job Search", emoji: "1f50e" },
      { name: "Networking", emoji: "1f91d" },
      { name: "Interviews", emoji: "1f3a4" },
      { name: "Offers & Negotiation", emoji: "1f4b8" },
      { name: "Career Development", emoji: "1f4da" },
    ],
  },
  {
    for: ["High school student"],
    category: "School",
    name: "High school Time Management",
    columns: [
      { name: "Assignments", emoji: "1f4d3" },
      { name: "Study Schedule", emoji: "1f4da" },
      { name: "Extracurriculars", emoji: "1f3c3" },
      { name: "To-Do List", emoji: "2705" },
      { name: "Upcoming Tests", emoji: "1f4c8" },
    ],
  },
  {
    for: ["College student"],
    category: "School",
    name: "College Time Management",
    columns: [
      { name: "Class Schedule", emoji: "1f5a5" },
      { name: "Assignments", emoji: "1f4dd" },
      { name: "Study Plan", emoji: "1f4da" },
      { name: "Projects", emoji: "1f4c0" },
      { name: "Exams", emoji: "1f4c3" },
      { name: "Personal Time", emoji: "1f3be" },
    ],
  },
  {
    for: ["College student", "Job seeker"],
    category: "Personal",
    name: "College/Career Planning",
    columns: [
      { name: "Research", emoji: "1f50e" },
      { name: "College Applications", emoji: "1f4d3" },
      { name: "Scholarships", emoji: "1f4b0" },
      { name: "Internships", emoji: "1f4bb" },
      { name: "Job Offers", emoji: "1f4e9" },
      { name: "Career Goals", emoji: "1f4ca" },
    ],
  },
  {
    for: ["Student"],
    category: "School",
    name: "School Project",
    columns: [
      { name: "Research", emoji: "1f50e" },
      { name: "Planning", emoji: "1f4c3" },
      { name: "Design", emoji: "1f3a8" },
      { name: "Presentation", emoji: "1f4e2" },
      { name: "Submission", emoji: "2705" },
    ],
  },
  {
    for: ["Student", "Theater enthusiast"],
    category: "School",
    name: "School Drama Play",
    columns: [
      { name: "Script Selection", emoji: "1f4da" },
      { name: "Casting", emoji: "1f3a5" },
      { name: "Rehearsals", emoji: "1f3ad" },
      { name: "Costume Design", emoji: "1f457" },
      { name: "Set Design", emoji: "1f3a8" },
      { name: "Props", emoji: "1f6cd" },
      { name: "Lighting and Sound", emoji: "1f4e3" },
      { name: "Promotion", emoji: "1f3ac" },
      { name: "Performance", emoji: "1f3a9" },
    ],
  },
  {
    for: ["Student", "Sports enthusiast"],
    category: "School",
    name: "School Sports Team",
    columns: [
      { name: "Practice Schedule", emoji: "1f3c3" },
      { name: "Drills and Skills", emoji: "1f3c8" },
      { name: "Game Strategy", emoji: "1f3af" },
      { name: "Team Communication", emoji: "1f4ac" },
      { name: "Fitness and Conditioning", emoji: "1f3cb" },
      { name: "Competitions", emoji: "1f3c5" },
      { name: "Team Bonding", emoji: "1f3d6" },
      { name: "Achievements", emoji: "1f3c6" },
    ],
  },
  {
    for: ["Shopper", "Home cook"],
    category: "Personal",
    name: "Grocery List",
    columns: [
      { name: "Produce", emoji: "1f955" },
      { name: "Meat", emoji: "1f356" },
      { name: "Bakery", emoji: "1f35e" },
      { name: "Snacks", emoji: "1f95d" },
      { name: "Miscellaneous", emoji: "1f4aa" },
    ],
  },
  {
    for: ["High School Club"],
    category: "School",
    name: "Club Management",
    columns: [
      { name: "Tasks", emoji: "1f4cb" },
      { name: "Projects", emoji: "1f4c3" },
      { name: "Events", emoji: "1f3c3" },
      { name: "Finance", emoji: "1f4b0" },
    ],
  },
  {
    for: ["Event planner", "Organizer"],
    category: "Work",
    name: "Event Planning Checklist",
    columns: [
      { name: "Preparation", emoji: "1f4cc" },
      { name: "Venue Selection", emoji: "1f3e2" },
      { name: "Logistics", emoji: "1f69a" },
      { name: "Marketing", emoji: "1f4f7" },
      { name: "Execution", emoji: "1f3ad" },
    ],
  },
  {
    for: ["Traveler", "Adventurer"],
    category: "Personal",
    name: "Travel Itinerary",
    columns: [
      { name: "Destination Research", emoji: "1f310" },
      { name: "Transportation", emoji: "1f698" },
      { name: "Accommodation", emoji: "1f3e8" },
      { name: "Sightseeing", emoji: "1f30d" },
      { name: "Activities", emoji: "1f3c6" },
    ],
  },
  {
    for: ["Project manager", "Team leader"],
    category: "Work",
    name: "Project Management",
    columns: [
      { name: "Planning", emoji: "1f4c3" },
      { name: "Tasks", emoji: "1f4cb" },
      { name: "In Progress", emoji: "1f4dd" },
      { name: "Review", emoji: "1f4ca" },
      { name: "Completed", emoji: "2705" },
    ],
  },
  {
    for: ["Book lover", "Reader"],
    category: "Personal",
    name: "Book Reading List",
    columns: [
      { name: "To Read", emoji: "1f4d6" },
      { name: "Currently Reading", emoji: "1f4da" },
      { name: "On Hold", emoji: "23f8" },
      { name: "Read", emoji: "1f4d2" },
      { name: "Favorites", emoji: "2764" },
    ],
  },
  {
    for: ["Budget-conscious individual", "Financial planner"],
    category: "Personal",
    name: "Budget Tracker",
    columns: [
      { name: "Income", emoji: "1f4b8" },
      { name: "Expenses", emoji: "1f4c9" },
      { name: "Savings", emoji: "1f4b0" },
      { name: "Debts", emoji: "1f4b7" },
      { name: "Financial Goals", emoji: "1f4b5" },
    ],
  },
  {
    for: ["Music lover", "Playlist curator"],
    category: "Personal",
    name: "Music Playlist",
    columns: [
      { name: "Upbeat", emoji: "1f3b5" },
      { name: "Relaxing", emoji: "1f3b6" },
      { name: "Energetic", emoji: "1f525" },
      { name: "Chill", emoji: "1f30a" },
      { name: "Favorites", emoji: "2665" },
    ],
  },
  {
    for: ["Team members", "Collaborators"],
    category: "Work",
    name: "Project Collaboration",
    columns: [
      { name: "Ideation", emoji: "1f4a1" },
      { name: "Tasks", emoji: "1f4cb" },
      { name: "In Progress", emoji: "1f4dd" },
      { name: "Review", emoji: "1f4ca" },
      { name: "Completed", emoji: "2705" },
    ],
  },
  {
    for: ["Entrepreneur", "Business owner"],
    category: "Work",
    name: "Business Plan",
    columns: [
      { name: "Executive Summary", emoji: "1f4cc" },
      { name: "Market Research", emoji: "1f50e" },
      { name: "Product/Service Offering", emoji: "1f4e6" },
      { name: "Marketing Strategy", emoji: "1f4f7" },
      { name: "Financial Projections", emoji: "1f4b8" },
    ],
  },
  {
    for: ["Business owner", "Accountant"],
    category: "Work",
    name: "Business Expense Tracker",
    columns: [
      { name: "Office Supplies", emoji: "1f4dd" },
      { name: "Travel Expenses", emoji: "1f698" },
      { name: "Utilities", emoji: "1f4e6" },
      { name: "Marketing Expenses", emoji: "1f4f7" },
      { name: "Miscellaneous", emoji: "1f4aa" },
    ],
  },
  {
    for: ["Programmer", "Software developer"],
    category: "Work",
    name: "Programming Project Tracker",
    columns: [
      { name: "Planning", emoji: "1f4c3" },
      { name: "Development", emoji: "1f4bb" },
      { name: "Testing", emoji: "1f50e" },
      { name: "Bugs/Issues", emoji: "1f41b" },
      { name: "Completed", emoji: "2705" },
    ],
  },
  {
    for: ["Software developer", "Tech enthusiast"],
    category: "Work",
    name: "Tech Stack Overview",
    columns: [
      { name: "Front-end", emoji: "1f3a7" },
      { name: "Back-end", emoji: "1f6e0" },
      { name: "Database", emoji: "1f4c1" },
      { name: "DevOps", emoji: "2699" },
      { name: "Other Tools", emoji: "1f4bb" },
    ],
  },
];
